display_name = "Isaac Policy Based Robot Control Examples"

[package]
version = "4.0.3"
category = "Simulation"
title = "Reinforcement Learning Inference Example for Robots in Isaac Sim"
description = "The Policy Based Robot Control Examples extension provides utilities for deploying reinforcement learning policies in Isaac Sim, as well as locomotion examples for humanoid and quadruped robots."
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "robot", "quadruped", "humanoid", "policy", "inference"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"

[dependencies]
"isaacsim.core.api" = {}
"isaacsim.sensors.physics" = {}
"isaacsim.core.nodes" = {}
"isaacsim.storage.native" = {}

[[python.module]]
name = "isaacsim.robot.policy.examples"

[[python.module]]
name = "isaacsim.robot.policy.examples.tests"
public = false

[[test]]
timeout = 900
stdoutFailPatterns.exclude = [
    '*[Error] [carb] [Plugin: omni.sensors.nv.lidar.ext.plugin] Dependency: [omni::sensors::lidar::IGenericModelOutputIOFactory v0.1] failed to be resolved.*', # feature not included in Windows
]

args = [
'--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
'--/persistent/isaac/asset_root/default = "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.5"',
]

[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]
