[core]
reloadable = true
order = 0

[package]
version = "2.0.2"
category = "Other"
title = "Isaac Sim Version"
description = "Isaac Sim Version extension provides tools to query Isaac Sim version and build information."
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"isaacsim.core.deprecation_manager" = {}


[[python.module]]
name = "isaacsim.core.version"

[[python.module]]
name = "isaacsim.core.version.tests"

[[test]]
dependencies = ["omni.kit.test"]
