name: isaac-sim
channels: 
  - defaults
  - pytorch
  - nvidia
dependencies: 
  - python=3.10
  - pip
  - pytorch 
  - torchvision 
  - torchaudio 
  - cuda-toolkit=11.8
  - pip:
    - tensorboard==2.18.0
    - tensorboard-plugin-wit==1.8.1 
    - protobuf==3.20.3
