[core]
reloadable = true
order = 0

[package]
version = "2.1.1"
category = "Simulation"
title = "Isaac Sim Surface Gripper UI Components"
description = "UI components for the Surface Gripper extension"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "physics", "end-effector","ui"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.gui.components" = {}
"isaacsim.robot.surface_gripper" = {}

[[python.module]]
name = "isaacsim.robot.surface_gripper.ui"