[core]
reloadable = true
order = 0

[package]
version = "1.0.5"
category = "Utility"
title = "VS Code integration"
description = "VS Code version of Omniverse's script editor"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "python", "vscode", "editor"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.uiapp" = { optional = true }
"omni.kit.notification_manager" = { optional = true }
"isaacsim.core.deprecation_manager" = {}

[[python.module]]
name = "isaacsim.code_editor.vscode"

[settings]
# IP address where the extension server will listen for connections.
exts."isaacsim.code_editor.vscode".host = "0.0.0.0"
# Port number where the extension server will listen for connections.
exts."isaacsim.code_editor.vscode".port = 8226
# Whether to publish incoming carb logging messages.
exts."isaacsim.code_editor.vscode".carb_logs = true
