[core]
reloadable = true
order = 0

[package]
version = "1.0.4"
category = "Simulation"
title = "Benchmark"
description = "This extension provides benchmarking utilities"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "benchmark", "analyze"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"isaacsim.benchmark.services" = {}
"isaacsim.sensors.camera" = {}
"isaacsim.sensors.physx" = {}
"isaacsim.sensors.rtx" = {}
"omni.graph.tools" = {}
"omni.graph.ui" = {}
"omni.graph" = {}
"omni.hydra.rtx"= {}
"omni.isaac.core_archive" = {} # pulls in nvsmi
"isaacsim.core.nodes" = {}
"isaacsim.core.api" = {}
"isaacsim.robot.wheeled_robots" = {}
"omni.kit.material.library"= {}
"omni.kit.primitive.mesh"= {}
"omni.kit.viewport.utility"= {}
"omni.kit.viewport.window"= {}
"omni.physx" = {}

[[python.module]]
name = "isaacsim.benchmark.examples"

[[test]]
# these are not cached
dependencies = [
    "isaacsim.storage.native" # test only
]

timeout = 900
args = [
"--no-window",
"--allow-root",
"--/app/fastShutdown=1",
"--vulkan",
'--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
'--/persistent/isaac/asset_root/default = "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.5"',
] # we can use fast shutdown because metrics are not uploaded

stdoutFailPatterns.exclude = [
    "*NGX EvaluateFeature failed*", # Ada multi gpu doesn't support this yet
    "*Failed to evaluate DLSS feature*", # Ada multi gpu doesn't support this yet
    '*[Error] [carb] [Plugin: omni.sensors.nv.lidar.ext.plugin] Dependency: [omni::sensors::lidar::IGenericModelOutputIOFactory v0.1] failed to be resolved.*', # feature not included in Windows
]


[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]
