[core]
reloadable = true
order = 0

[package]
version = "2.0.3"
category = "Simulation"
title = "Gain Tuner"
description = "Gain Tuner for Articulation PD Gains"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "physics", "analyze", "tune"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"omni.kit.uiapp" = {}
"isaacsim.gui.components" = {}
"isaacsim.core.api" = {}
"isaacsim.core.deprecation_manager" = {}

[[python.module]]
name = "isaacsim.robot_setup.gain_tuner"