[core]
reloadable = true
order = 0

[package]
version = "1.1.3"
category = "Simulation"
title = "Isaac Sim UI Example"
description = "Example with all the Core UI Elements in Isaac Sim"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "example", "ui",]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"

[dependencies]
"omni.kit.uiapp" = {}
"isaacsim.gui.components" = {}
"isaacsim.examples.browser" = {}

[[python.module]]
name = "isaacsim.examples.ui"

[[python.module]]
name = "isaacsim.examples.ui.tests"
