[core]
reloadable = true
order = 0

[package]
version = "2.2.3"
category = "SyntheticData"
title = "Isaac Sim Replicator Synthetic Data Recorder"
description = "The extension provides a UI to record synthetic data using Replicator writers. By default the UI uses the Replicator BasicWriter, it however also supports custom writers with custom parameters loaded through config files as key-value pairs."
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "synthetic", "recorder", "sdg"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"omni.replicator.core" = {}
"omni.timeline" = {}
"omni.kit.viewport.utility" = {}
"omni.kit.window.extensions" = {}

[[python.module]]
name = "isaacsim.replicator.synthetic_recorder"

[[test]]
dependencies = [
    "omni.kit.test"
]
args = [
'--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]

[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]
