[core]
reloadable = true
order = 0

[package]
version = "2.0.3"
category = "Simulation"
title = "Isaac Cortex Sample Behaviors"
description = "Library of Sample Behaviors for Isaac Cortex used in our core examples. It contains a pick and place state machine used on a UR10 for bin stacking, and six examples used on a Franka robot, namely a simple decider network and a state machine, block stacking, and Peck game, state machine and decider network behaviors."
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "samples", "manipulation"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.core.api" = {}
"isaacsim.cortex.framework" = {}

[[python.module]]
name = "isaacsim.cortex.behaviors"


[[test]]

args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]

[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]