[core]
reloadable = true
order = 0

[package]
version = "3.1.5"
category = "Simulation"
title = "Robot Description Editor"
description = "Generates and edit Lula robot_description YAML files"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "collision spheres", "lula", "robot description"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"


[dependencies]
"omni.kit.uiapp" = {}
"isaacsim.gui.components" = {}
"isaacsim.core.api" = {}
"isaacsim.core.deprecation_manager" = {}
"isaacsim.robot_motion.lula" = {}


[[python.module]]
name = "isaacsim.robot_setup.xrdf_editor"
