[core]
reloadable = true
order = 0

[package]
version = "2.0.6"
category = "Simulation"
title = "Isaac Sim Surface Gripper"
description = "Helper to model Suction and Distance based grippers"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "physics", "end-effector",]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true
writeTarget.platform = true

[dependencies]
"omni.isaac.dynamic_control" = {}
"isaacsim.gui.components" = {}
"isaacsim.core.deprecation_manager" = {}
"isaacsim.core.api" = {}
"omni.graph.tools" = {}
"omni.graph" = {}

# Watch the .ogn files for hot reloading (only for Python files)
[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py"]

[[python.module]]
name = "isaacsim.robot.surface_gripper"

[[python.module]]
name = "isaacsim.robot.surface_gripper.tests"

[[test]]
dependencies = ["isaacsim.core.utils"]
stdoutFailPatterns.exclude = [
    "*[Error] [carb.glinterop.plugin] GLInteropContext::init: carb::windowing is not available*",
]