[core]
reloadable = true
order = 0

[package]
version = "1.0.1"
category = "SyntheticData"
title = "Isaac Sim Replicator Writers"
description = "The extension provides various custom Replicator based writers for Synthetic Data Generation (SDG) workflows. The writers are registered with Replicator at extension startup."
authors = ["NVIDIA"]
repository = ""
keywords = ["Synthetic", "Data", "Generation", "SDG", "Writers"]
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"

# Build separate extensions for Windows and Linux so appropriate libraries are bundled
writeTarget.platform = true


[dependencies]
"omni.graph" = {}
"omni.graph.core" = {}
"isaacsim.core.api" = {}
"omni.replicator.core" = {}
"omni.isaac.ml_archive" = {} # torch

[[python.module]]
name = "isaacsim.replicator.writers"

# Watch the .ogn files for hot reloading (only works for Python files)
[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py"]

[[test]]
dependencies = [
    "omni.kit.test",
]
args = [
'--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]

[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]