[core]
reloadable = true
order = 0

[package]
version = "1.1.3"
category = "Simulation"
title = "Isaac Sim USD to URDF exporter"
description = "Extension that exports USD files to URDF"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "URDF"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true
writeTarget.platform = true # pip prebundle makes this extension os specific

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"omni.kit.pip_archive" = {}
"isaacsim.gui.components" = {}
"isaacsim.core.utils" = {}

[[python.module]]
path = "pip_prebundle"

[[python.module]]
name = "isaacsim.asset.exporter.urdf"

[[python.module]]
name = "isaacsim.asset.exporter.urdf.tests"

[[test]]

dependencies = [
    "omni.kit.test"
]
