[core]
reloadable = true
order = 0

[package]
version = "1.0.6"
category = "Other"
title = "Isaac Sim Import Wizard [alpha]"
description = "wizard to guide users through importing and configuration tools inside isaac sim"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac","wizard","import"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"isaacsim.gui.components" = {}
"omni.kit.menu.utils" = {}
"omni.physx.supportui" = {}

[[python.module]]
name = "isaacsim.robot_setup.import_wizard"
